# Site settings
title: Ismael Soares
email: rkmael@hotmail.com
description: "Olá seja bem vindo ao blog do Ismael Soares. Compartilho aqui meus estudos sobre TDD, BDD, Tech Talks, Gestão e Banco de dados e meus pensamentos ágeis."
baseurl: ""
url: "http://rkmael.com"
twitter_username: rkmael
github_username:  rkmael
facebook_username: ismael.soares.351

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["node_modules"]
comments: true
gems:
  - jekyll-sitemap