# Site settings
title: Ismael Soares
email: rkmael@hotmail.com
description: "Blog de Agilidade do Ismael Soares"
baseurl: ""
url: "http://rkmael.com"
twitter_username: rkmael
github_username:  rkmael
facebook_username: ismael.soares.351

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["node_modules"]
comments: true
gems:
  - jekyll-sitemap